### CONFIGURATION

# For example: remove '#' from the following line to split your documents by chapter
#SPLITAT = chapter

# remove '#' from the following line to split template.tex by section
#template_SPLITAT=section

# see https://vlmantova.github.io/bookml/ for the full list of options

include bookml/bookml.mk
