### GLOBAL CONFIGURATION
# Remove the initial '#' and change the value to customise the build process
#
# Options can also be customized on the command line, for instance
#   make SPLITAT= singlepage.zip
# will compile singlepage.tex into a single page
#
# For example: remove '#' below to split your document by chapter

#SPLITAT = chapter

### END GLOBAL CONFIGURATION

include bookml/bookml.mk

### LOCAL CONFIGURATION
# Remove the initial '#' and change file names and values to customise the build
# for a particular output file
#
# For example: remove '#' below to split template.zip, SCORM.template.zip by chapter

#template.zip SCORM.template.zip: SPLITAT=

### END LOCAL CONFIGURATION
