SOURCES=$(wildcard amsldoc-equations-*.tex disable-mathjax-*.tex latexml-t-ams-mathtools-*.tex mathtools-*.tex mathvariants-*.tex tests.tex)
TARGETS=$(TARGETS.HTML)
SPLITAT=

html:
-include bookml/bookml.mk
