### CONFIGURATION

# For example: remove '#' from the following line to split your documents by chapter
#SPLITAT = chapter

# remove '#' from the following line to not split exercises and exercises+solutions
# example will still be split by section, if there are any
#exercises_SPLITAT=
#exercises_solutions_SPLITAT=

# see https://vlmantova.github.io/bookml/ for the full list of options

include bookml/bookml.mk
