# BookML: bookdown flavoured GitBook port for LaTeXML
# Copyright (C) 2021-26 Vincenzo Mantova <v.l.mantova@leeds.ac.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ifndef __bml.deps.mk.included
__bml.deps.mk.included :=

### Dependency tracking

include bookml/bml-version.mk
include bookml/bml-utils.mk

# The files that contribute to building a PDF, XML, or HTML file are stored in
# the autogenerated makefiles in $(AUX_DIR)/deps folder.
#
# The makefiles are used to determine:
# - whether a file is out of date and needs to be recompiled, based on whether
#   all included .tex files, bibliography, figures, etc. have changed
# - which other files must be compiled first, for instance the PDFs that must
#   must be included in the HTML outputs
#
# The makefiles are remade automatically by GNU Make, which restarts itself
# until all makefiles are up to date. Since this is very costly for .tex files,
# we do a single, dry run recursive call to determine which files the user is
# trying to build, and regenerate their makefiles only.
#
# Remaking makefiles also allows us to track dependencies that may be circular,
# such as the ones created by xr, even though GNU Make can only deal with
# directed acyclic graphs.

# the parameter bml.deps.recordupdates asks that all $(AUX_DIR) recipes print,
# in a machine-recognisable format, which outputs are meant to be built
ifdef bml.deps.recordupdates
  bml.deps.recordupdate   = $(info bookml-update:$(subst $(AUX_DIR)/,$$(AUX_DIR)/,$(subst $$,$$$$,$@)))
  bml.deps.updates       :=
else
  bml.deps.recordupdate  :=
  bml.deps.recordupdates :=

  bml.deps.makeoverrides :=

  # pass overrides from the command line (already in MAKEFLAGS since 4.4.1)
  ifneq ($(call bml.version.lt,$(MAKE_VERSION),4.4.1),)
    # overrides are escaped via '$' -> '$$', ' ' -> '\ ', '\' -> '\\' (see
    # quote_for_env in main.c), then concatenated by spaces in reverse order

    # undo both reverse concatenation and quoting, and apply shell escaping
    # a string of backslashes of odd length signals an escaped space: detect
    # this by halving then doubling all runs of backslashes
    $(eval o:=) # accumulator for the current override
    $(foreach ovd,$(MAKEOVERRIDES),$(eval s:=$$(subst $$(ovd),,$$(subst \,\\,$$(subst \\,\,$$(ovd))))) \
      $(eval o:=$$(if $$o,$$o ,)$$(subst $$$$$$$$,$$$$,$$(subst \\,\,$$(subst $$s ,,$$(ovd) )))) \
      $(if $s,, \
        $(eval bml.deps.makeoverrides:=$$(call bml.utils.escapearg,$$o) $$(bml.deps.makeoverrides)) \
        $(eval o:=)))
  endif

  # note: MAKECMDGOALS does not escape spaces in any way
  bml.deps.goals := $(foreach goal,$(MAKECMDGOALS),$(call bml.utils.escapearg,$(goal)))

  # smuggle values that are costly to compute, especially bml.autosources
  $(foreach var,bml.autosources TEXFOT ZIP UNZIP CURL,$(eval bml.deps.makeoverrides := $$(bml.deps.makeoverrides) $$(call bml.utils.escapearg,$$(var)=$$(subst $$$$,$$$$$$$$,$$($$(var))))))

  bml.deps.makeopts      := $(if $(call bml.version.leq,4,$(MAKE_VERSION)),-Oline)
  bml.deps.makeoverrides := $(bml.deps.makeoverrides) bml.deps.recordupdates=true
  bml.deps.makeflags     := -n -s -f $(firstword $(MAKEFILE_LIST))

  bml.deps.makecall = $(MAKE) $(bml.deps.makeflags) $(bml.deps.makeopts) -- $(bml.deps.makeoverrides) $(bml.deps.goals)

  # optimisation: XML files should never cause additional work just because of
  # the content of xml.mk (while HTML and PDF may require figures or refer to
  # other PDFs via xr), so rebuild the deps coming from XML first
  bml.deps.output  := $(shell $(bml.deps.makecall))
  bml.deps.updates := $(subst $$(AUX_DIR),$(AUX_DIR),$(filter $$(AUX_DIR)/xml/%,$(call bml.utils.filtersubst,bookml-update:%,%,$(bml.deps.output))))
  # once all XML files are fresh, check the entire dependency tree, even if
  # considered fresh, to cause indirect dependencies (via xr) to build
  ifeq ($(strip $(bml.deps.updates)),)
    bml.deps.makeopts += -B
    bml.deps.output   := $(shell $(bml.deps.makecall))
    bml.deps.updates  := $(subst $$(AUX_DIR),$(AUX_DIR),$(call bml.utils.filtersubst,bookml-update:%,%,$(bml.deps.output)))
  endif

  bml.deps.rebuild := $(sort \
    $(call bml.utils.filtersubst,$(AUX_DIR)/xml/%.preprocessed-xml,$(AUX_DIR)/deps/%.tex/html.mk,$(bml.deps.updates)) \
    $(call bml.utils.filtersubst,$(AUX_DIR)/xml/%.xml,$(AUX_DIR)/deps/%.tex/xml.mk,$(bml.deps.updates)) \
    $(call bml.utils.filtersubst,$(AUX_DIR)/pdf/%.pdf,$(AUX_DIR)/deps/%.tex/pdf.mk,$(bml.deps.updates)) \
    $(call bml.utils.filtersubst,$(AUX_DIR)/pdf/%.xraux,$(AUX_DIR)/deps/%.tex/pdf.mk,$(bml.deps.updates)) \
    $(filter $(AUX_DIR)/deps/%.mk,$(MAKECMDGOALS)))
endif

# avoid unnecessary rebuilds if cleaning or updating
ifneq ($(filter check-for-update clean clean-% update,$(bml.utils.makecmdgoals)),)
  # refuse to build files
  $(if $(filter-out check-for-update clean-% clean update,$(bml.utils.makecmdgoals)),$(call bml.print.error,Compiling targets while cleaning or updating is not supported!))
  # no file will be compiled
  override bml.deps.updates :=
  override bml.deps.rebuild :=
endif

# avoid rebuilding deps if it is a dry run
ifneq ($(bml.utils.isdryrun),)
  override bml.deps.updates :=
  override bml.deps.rebuild :=
endif

# PDF may depend on .aux files of other PDFs (via xr)
bml.deps.xraux :=

# let Make fail if the deps fail to build, or it will go in an infinite loop
ifneq ($(bml.utils.isdryrun),)
  -include $(filter %.mk,$(call bml.utils.tree,$(AUX_DIR)/deps))
else
  include $(sort $(bml.deps.rebuild))
  -include $(filter-out $(bml.deps.rebuild),$(filter %.mk,$(call bml.utils.tree,$(AUX_DIR)/deps)))
  $(if $(and $(call bml.version.lt,$(MAKE_VERSION),4.2),$(strip $(foreach dep,$(sort $(bml.deps.rebuild)),$(if $(wildcard $(dep)),,m)))),$(call bml.print.warning,warnings about missing deps/.../*.mk files can be ignored, they will be built now))
endif

### xr support
# xr is allowed to introduce circular dependencies between PDFs, which Make
# does not and cannot support. We address the issue as follows.
#
# To avoid circular dependencies:
# - every PDF is accompanied by an .xraux file that summarises the content
#   that would be read by other PDFs using xr
# - the .xraux file is only updated if its content changes
# - if a PDF calls xr, it becomes dependent on .xraux, and will be recompiled
#   after make parse its regenerated dep file
#
# To avoid inconsistencies when parallel building:
# - every PDF is timestamped to when the compilation started
# - the PDF file also depends on .xraux, ensuring that the PDF is up
#   to date only if it started compiling after .xraux was completed
#
# Moreover, a PDF and its prerequisites .xraux cannot be built in parallel.
# We prevent this by introducing order-only dependencies between PDFs that
# are immediately dependent on each other.
#
# To avoid circular dependencies, and minimize the number of edges, we take a
# minimal acyclic subgraph with the following property: if two vertices are
# adjacent, then they are 'unilaterally connected' in the subgraph, that is,
# there is a path between them in *some* direction.
#
# Since order-only dependencies are transitive, adjacent targets are then
# guaranteed to be built serially.

# Too many edges can trigger a virtually infinite loop, so we avoid it when
# already building serially (but only GNU Make 4.3 and later make this visible)
# we can also skip this in the recursive make call
ifneq ($(and $(bml.deps.xraux),\
  $(if $(bml.deps.recordupdates)$(filter clean clean-% detect detect-%,$(bml.utils.makecmdgoals)),,ok),\
  $(or $(call bml.version.lt,$(MAKE_VERSION),4.3),\
    $(filter-out -j1,$(filter -j%,$(bml.utils.makeopts))))),)

bml.xraux.edges := $(sort $(bml.deps.xraux))
$(call bml.print.info,$(bml.print.magenta)xr: found $(words $(bml.xraux.edges)) dependenc$(if $(filter 1,$(words $(bml.xraux.edges))),y,ies) between PDF files)

# represent the directed graph of dependencies as a list of target:prerequisite
bml.xraux.targets := $(sort $(foreach edge,$(bml.xraux.edges),$(word 1,$(subst :, ,$(edge)))))
bml.xraux.prereqs := $(sort $(foreach edge,$(bml.xraux.edges),$(word 2,$(subst :, ,$(edge)))))

bml.xraux.subgraph :=
bml.xraux.closure  :=
bml.xraux.visited :=

# Compute the desired subgraph and its transitive closure incrementally.
# Remember that the transitive closure of a graph contains an edge t:p when
# there is a path from t to p in the graph. Minimality is equivalent to
# requiring that every edge t:p is the only path from t to p.
#
# Given an edge e of the original graph and an acyclic subgraph G:
# - if e is in the transitive closure of G, skip
# - compute the new edges of the transitive closure of G + e, given by the
#   paths going through e, and add them to the closure
# - remove the new edges from the G (acyclicity ensures that the closure of
#   G + e is preserved: the paths through e consists only of old edges and e)
# - add e to G
bml.xraux.addedge   = $(if $(filter $1:$2 $2:$1,$(bml.xraux.closure)),, \
  $(eval ts:=$$1: $$(call bml.utils.filtersubst,%:$$1,%:,$$(bml.xraux.closure))) \
  $(eval ps:=$$2 $$(call bml.utils.filtersubst,$$2:%,%,$$(bml.xraux.closure))) \
  $(eval n :=$$(foreach target,$$(ts),$$(addprefix $$(target),$$(ps)))) \
  $(eval bml.xraux.closure  += $$1:$$2 $$(filter-out $$(bml.xraux.closure),$$n)) \
  $(eval bml.xraux.subgraph := $$(filter-out $$n,$$(bml.xraux.subgraph)) $$1:$$2))

bml.xraux.traverse = $(foreach target,$1,$(eval bml.xraux.visited += $$(target)) \
  $(foreach prereq,$(call bml.utils.filtersubst,$(target):%,%,$(bml.xraux.edges)), \
    $(call bml.xraux.addedge,$(target),$(prereq)) \
    $(if $(filter $(prereq),$(bml.xraux.visited)),,$(call bml.xraux.traverse,$(prereq)))))

$(call bml.xraux.traverse,$(bml.xraux.targets))

bml.xraux.rules :=  $(subst $(bml.utils.space)$(bml.utils.nl),$(bml.utils.nl),$(patsubst %:,$(bml.utils.nl)%:,$(foreach target,$(bml.xraux.targets),\
    $$(AUX_DIR)/pdf/$(target).pdf: | $(call bml.utils.filtersubst,$(target):%,$$(AUX_DIR)/pdf/%.pdf,$(bml.xraux.subgraph)))\
  $(patsubst %,$$(AUX_DIR)/pdf/%.pdf:,$(bml.xraux.prereqs))))

$(call bml.print.info,$(bml.print.magenta)xr: dependency graph reduced to $(words $(bml.xraux.subgraph)) non-circular dependenc$(if $(filter 1,$(words $(bml.xraux.subgraph))),y,ies))
$(call bml.print.info,$(bml.print.magenta)xr: if make gets stuck with high CPU usage$(bml.utils.comma)$(if $(call bml.version.lt,$(MAKE_VERSION),4.3), upgrade your version of GNU Make and) disable parallel building)

# uncomment the line below to help debug xr issues
$(file > $(AUX_DIR)/deps/xraux.rules,$(bml.xraux.rules))
$(eval $(bml.xraux.rules))

endif

endif # __bml.deps.mk.included
