### TeX Live base image
FROM ubuntu:24.04

# equivs brings in a lot of dependencies, unfortunately
ARG DEBIAN_FRONTEND=noninteractive
RUN set -ex && apt update -qq && apt install -qy tzdata curl perl-modules && apt install -qy equivs --no-install-recommends

# TL 2021 is the latest version for which expl3 loads in reasonable time
ARG TEXLIVE_VERSION=2021
LABEL org.opencontainers.image.source=https://github.com/vlmantova/bookml
LABEL org.opencontainers.image.title="TeX Live ${TEXLIVE_VERSION} base for BookML"
LABEL org.opencontainers.image.description="TeX Live ${TEXLIVE_VERSION} base for BookML"

# install fake texlive-local package
# remove dependency on freeglut3
RUN set -ex && curl -L "https://wiki.debian.org/TeXLive?action=AttachFile&do=get&target=debian-equivs-${TEXLIVE_VERSION}-ex.txt" | grep -v Depends: > /tmp/texlive-equiv
RUN set -ex && cd /tmp && equivs-build texlive-equiv && dpkg -i texlive-local_*.deb
RUN rm -fr /tmp/*

# install TeX Live
RUN set -ex && cd /tmp && curl -L https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/${TEXLIVE_VERSION}/install-tl-unx.tar.gz | tar xzv

COPY <<EOF /tmp/texlive.profile
instopt_adjustpath 1
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
EOF
RUN set -ex && cd /tmp && perl install-tl-*/install-tl --repository https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/${TEXLIVE_VERSION}/tlnet-final --profile /tmp/texlive.profile
